---
Name: appconfig
---
SilverStripe\i18n\i18n:
  default_locale: 'en_GB'

Axllent\ScaledUploads\ScaledUploads:
  max_width: 1920
  max_height: 1920

ilateral\SilverStripe\Searchable\Searchable:
  objects:
    "Page": ["Title","MenuTitle","Content","URLSegment"]
    "Product": ["Title","Content","URLSegment"]
    "Category": ["Title","Content","URLSegment"]

ilateral\SilverStripe\CustomMenus\Model\CustomMenuLink:
  base_classes:
    "Category": "A Product Category"
    "Product": "A Product"

ilateral\SilverStripe\Users\Users:
  require_verification: false
  send_verification_email: false

SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
    default_spam_protector: UndefinedOffset\NoCaptcha\Forms\NocaptchaProtector